### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by Ben-Ortiz** [QihanLu/CS419#1]
No new user registering feature and can't login.

**Comment by Kagesss** [comment]
**Thanks for your feedback!** Because this is a database that is designed for a company and we decide to **only allow an admin** (which is the big boss of the company) to add new users, so there is no registering feature for individuals. But you can add a new user by logging in as admin. Those are all pointed out in README.pdf, with the username and password of the admin.

**Comment by Kagesss** [comment]
And also could you please tell us more about can't log in? What error is shown when you are trying to log in?

**Comment by Ben-Ortiz** [comment]
I see so you can only login as admin. I assumed you could login as any user. But I see only admin account is allowed.

**Comment by Kagesss** [comment]
Yes! You can only start as an admin, meaning that you must log in as admin on your first try, then you can create as many users as you want as an admin and only admin. After the admin added other users to the user list. You can log in as another user you are added.

**Comment by Ben-Ortiz** [comment]
Got it I'll try that

**Comment by symxmyz233** [comment]
**Not a bug**
